Blog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class Post
    {
        public int Id { get; set; }

        [DisplayName("Дата")]
        public DateTime? Date { get; set; }

        [DisplayName( "Заголовок")]
        [StringLength(100, ErrorMessage = "Заголовок не может привышать 100 символов")]
        [Required(ErrorMessage = "Не набран заголовок поста")]
        public string Title { get; set; }

        [DisplayName("Описание")]
        [Required(ErrorMessage = "Не набрано описание поста")]
        public string Description { get; set; }


        [DisplayName("Текcт")]
        [Required(ErrorMessage = "Не набран текст поста")]
        public string Text { get; set; }


        public IEnumerable<Comment> Comments;

        [DisplayName("Разрешить комментарии")]
        [Required]
        public bool AllowComments { get; set; }

        [DisplayName("Автоматически добавлять комментарии без проверки админом")]
        [Required]
        public bool AutoExceptComments { get; set; }
    }
}

Blog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using PagedList;

namespace Blog.Controllers
{
    public class CommentsController : Controller
    {




        private BlogContext db = new BlogContext();

        public ActionResult Index()
        {
            return RedirectToAction("EditList");
        }

        public ActionResult EditList(int? id, int? page)
        {
            //количество сообщений на одну страницу
            int pageSize = 3;

            int pageNumber = page ?? 1;

            int count = db.Comments.Count();
            if (page == null && count > 0) pageSize = count;

            var comments = db.Comments
                .OrderByDescending(p => p.Id)
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .Include(c => c.Post)
                .ToList();

            var pagedComments = new StaticPagedList<Comment>(comments, pageNumber, pageSize, count);

            ViewBag.AllCommentsCount = count;
            ViewBag.NewCommentsCount = db.Comments.Count(c => c.IsSeenByAdmin == false);
            ViewBag.Title = "Все комментарии";
            return View(pagedComments);
        }

        public ActionResult EditListNewOnly(int? id, int? page)
        {
            //количество сообщений на одну страницу
            int pageSize = 3;

            int pageNumber = page ?? 1;

            int count = db.Comments
                .Count(c => c.IsSeenByAdmin == false);
            if (page == null && count > 0) pageSize = count;

            var comments = db.Comments
                .Where(c => c.IsSeenByAdmin == false)
                .OrderByDescending(p => p.Id)
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .Include(c => c.Post)
                .ToList();

            var pagedComments = new StaticPagedList<Comment>(comments, pageNumber, pageSize, count);

            ViewBag.AllCommentsCount = db.Comments.Count();
            ViewBag.NewCommentsCount = count;
            ViewBag.Title = "Новые комментарии";
            return View("EditList", pagedComments);
        }

        public ActionResult EditListPartial(int? id, int? page)
        {
            //количество сообщений на одну страницу
            int pageSize = 3;

            if (id == null) return HttpNotFound();

            int pageNumber = page ?? 1;
            int count = db.Comments.Count(c => c.PostId == id);
            if (page == null && count > 0) pageSize = count;

            var comments = db.Comments
                .Where(c => c.PostId == id)
                .OrderByDescending(p => p.Id)
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var pagedComments = new StaticPagedList<Comment>(comments, pageNumber, pageSize, count);

            return PartialView("_EditList", pagedComments);
        }



        public ActionResult ListPartial(int? id, int? page)
        {
            //количество сообщений на одну страницу
            int pageSize = 3;

            int pageNumber = page ?? 1;

            if (id == null) return HttpNotFound();

            int count = db.Comments
                    .Where(c => c.PostId == id)
                    .Count(c => c.IsAllowedByAdmin == true);
  
            if (page == null && count>0) pageSize = count;

              var comments = db.Comments
                    .Where(c => c.PostId == id)
                    .Where(c => c.IsAllowedByAdmin == true)
                    .OrderByDescending(p => p.Id)
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();

            var pagedComments = new StaticPagedList<Comment>(comments, pageNumber, pageSize, count);

            return PartialView("_List", pagedComments);
        }

      


        public ActionResult Create()
        {
           Comment comment = new Comment
           {
               Date = DateTime.Now,
               IsAllowedByAdmin = true,
               IsSeenByAdmin = true
           };
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title");
            return View(comment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Author,PostId,IsSeenByAdmin,IsAllowedByAdmin,Date,Text")] Comment comment)
        {
            Post post = db.Posts.FirstOrDefault(p => p.Id == comment.PostId);
            if (post == null) ModelState.AddModelError("PostId", "Не найден пост, соответствующий комментарию.");
            else
            {
                comment.Post = post;
                ModelState["Post"].Errors.Clear();
                TryUpdateModel(comment);
            }
                if (comment.Date == null) comment.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
            return View(comment);

        }

        public ActionResult CreatePartial(int? id)
        {
            if (id == null) return HttpNotFound();

            Post post = db.Posts.FirstOrDefault(p => p.Id == id);

            if (post == null) return HttpNotFound();

            Comment comment = new Comment { PostId = id };
            return PartialView("_Create", comment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePartial([Bind(Include = "Author,PostId,Text")] Comment comment)
        {
            //временной интервал (секунд) в течении которого невозможна повторная отправка комментариев
            const int commentsDelay = 10;

            Post post = db.Posts.FirstOrDefault(p => p.Id == comment.PostId);
            if (post == null) ModelState.AddModelError("", "Не найден пост, соответствующий комментарию.");
            else
            {
                comment.Post = post;
                ModelState["Post"].Errors.Clear();
                TryUpdateModel(comment);
            }


            comment.Date = DateTime.Now;


            Comment lastComment = db.Comments.Where(c => c.Author == comment.Author).OrderByDescending(c=>c.Date).FirstOrDefault();
            if (lastComment != null)
            {
                if (lastComment.Date > DateTime.Now.AddSeconds(-commentsDelay))
                    ModelState.AddModelError("", "В целях безопасности введено ограничение: не более 1 комментария в "
                                                 + commentsDelay + " секунд. Подождите "
                                                 +
                                                 (lastComment.Date - DateTime.Now.AddSeconds(-commentsDelay)).Value
                                                     .Seconds
                                                 + " секунд и повторите.");

            }

            if (ModelState.IsValid)
            {
                if (post.AutoExceptComments)
                    comment.IsAllowedByAdmin = true;
                else
                    comment.IsAllowedByAdmin = false;

                comment.IsSeenByAdmin = false;

                db.Comments.Add(comment);
                db.SaveChanges();

                if (post.AutoExceptComments)
                    return Content("Ваш комментарий опубликован. Спасибо.");
                else
                    return Content("Ваш комментарий принят и будет обработан администратором. Спасибо.");
            }

            return PartialView("_Create", comment);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null) return HttpNotFound();

            Comment comment = db.Comments.FirstOrDefault(c => c.Id == id);
            if (comment == null) return HttpNotFound();
   
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Author,PostId,IsSeenByAdmin,IsAllowedByAdmin,Date,Text")] Comment comment)
        {
            Post post = db.Posts.FirstOrDefault(p => p.Id == comment.PostId);
            if (post == null) ModelState.AddModelError("PostId", "Не найден пост, соответствующий комментарию.");
            else
            {
                comment.Post = post;
                ModelState["Post"].Errors.Clear();
                TryUpdateModel(comment);
            }
            if (comment.Date == null) comment.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
            return View(comment);
        }

  
        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();

            Comment comment = db.Comments.FirstOrDefault(c => c.Id == id);
            if (comment == null) return HttpNotFound();

            db.Comments.Remove(comment);
            db.SaveChanges();

            return RedirectToAction("EditList");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Allow(int id)
        {
            if (id == null) return HttpNotFound();

Blog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using PagedList;

namespace Blog.Controllers
{
    public class PostsController : Controller
    {
        private BlogContext db = new BlogContext();



        public ActionResult Index(int page = 1)
        {
            int pageSize = 3;

            int count = db.Posts.Count();
            var posts = db.Posts.OrderByDescending(p => p.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            var pagedPosts = new StaticPagedList<Post>(posts, page, pageSize, count);

            return View(pagedPosts);
        }

        // GET: Posts
        public ActionResult List(int page = 1)
        {
            int pageSize = 10;

            int count = db.Posts.Count();
            var posts = db.Posts.OrderByDescending(p => p.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            var pagedPosts = new StaticPagedList<Post>(posts, page, pageSize, count);

            ViewBag.PostsCount = count;
            return View(pagedPosts);
        }

        public ActionResult Show(int? id)
        {
            if (id == null) return HttpNotFound();

            Post post = db.Posts.FirstOrDefault(p => p.Id == id);

            if (post == null) return HttpNotFound();
            return View(post);
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return HttpNotFound();

            Post post = db.Posts.FirstOrDefault(p => p.Id == id);

            if (post == null) return HttpNotFound();
            return View(post);
        }



        public ActionResult Edit(int? id)
        {
            if (id == null) return HttpNotFound();

            Post post = db.Posts.FirstOrDefault(p => p.Id == id);

            if (post == null) return HttpNotFound();
            return View(post);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,Title,Description,Text,AllowComments")] Post post)
        {
            if (ModelState.IsValid)
            {
                if (post.Date == null) post.Date = DateTime.Now;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(post);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();

            Post post = db.Posts.FirstOrDefault(p => p.Id == id);

            if (post == null) return HttpNotFound();
            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            Post post = new Post();
            post.Date = DateTime.Now;
            post.AllowComments = true;
            post.AutoExceptComments = false;

            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Date,Title,Description,Text,AllowComments")] Post post)
        {
            if (ModelState.IsValid)
            {
                if (post.Date == null) post.Date = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(post);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();

            base.Dispose(disposing);
        }
    }
}

Blog/Views/Posts/Create.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Новый пост";
}

<h2>Новый пост</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="panel panel-default">
            <div class="panel-heading">
                Новый пост
            </div>
            <div class="panel-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-sm-2"})
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Description, 20, 10, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Text, htmlAttributes: new {@class = "control-label col-sm-2"})
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Text, 20, 10, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Text, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AllowComments, htmlAttributes: new {@class = "control-label col-sm-2"})
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.AllowComments, new {@class = "form-control checkbox"})
                        @Html.ValidationMessageFor(model => model.AllowComments, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AutoExceptComments, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.AutoExceptComments, new { @class = "form-control checkbox" })
                        @Html.ValidationMessageFor(model => model.AutoExceptComments, "", new { @class = "text-danger" })
                    </div>
                </div>


                <hr />
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        @Html.ActionLink("Отменить", "List", null, new { @class = "btn btn-default" })
                        <input type="submit" value="Опубликовать пост" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>


    </div>


}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Posts/Delete.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить пост</h2>




<div class="panel panel-danger">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        Вы уверены, что действительно хотите удалить этот пост?
    </div>
    <div class="panel-body">
        <div class="container">
            
            <h5><small>@Model.Date</small></h5>
            <h2>@Model.Title</h2>
            <hr/>
            <p>@Model.Text</p>
            <hr/>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                @Html.ActionLink("Отменить", "List", null, new { @class = "btn btn-default" })
                <input type="submit" value="Удалить" class="btn btn-danger" />
            </div>
        }
        </div>
    </div>

Blog/Views/Posts/Details.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Пост #@Model.Id</h2>


<div class="panel panel-default">
    <div class="panel-heading">
        Пост #@Model.Id
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Date)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Text)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.Text)
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.AllowComments)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.AllowComments)
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.AutoExceptComments)
            </div>
            <div class="col-sm-10">
                @Html.DisplayFor(model => model.AutoExceptComments)
                <br><br>
            </div>
        </div>


        <div class="row">
            <div class="col-sm-offset-2 col-sm-10">
                <hr />
                @Html.ActionLink("Список всех постов", "List", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Удалить пост", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Редактировать пост", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>


@Html.Action("EditListPartial", "Comments", new { id = Model.Id})

@if (Model.AllowComments)
{
    @Html.Action("CreatePartial", "Comments", new { id = Model.Id })
}

Blog/Views/Posts/Edit.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Редактирование поста";
}

<h2>Редактирование поста</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="panel panel-default">
            <div class="panel-heading">
                Редактирование поста
            </div>
            <div class="panel-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Description, 20, 10, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Text, htmlAttributes: new {@class = "control-label col-sm-2"})
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Text, 20, 10, new {@class = "form-control"})
                        @Html.ValidationMessageFor(model => model.Text, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AllowComments, htmlAttributes: new {@class = "control-label col-sm-2"})
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.AllowComments, new {@class = "form-control checkbox"})
                        @Html.ValidationMessageFor(model => model.AllowComments, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AutoExceptComments, htmlAttributes: new { @class = "control-label col-sm-2" })
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.AutoExceptComments, new { @class = "form-control checkbox" })
                        @Html.ValidationMessageFor(model => model.AutoExceptComments, "", new { @class = "text-danger" })
                    </div>
                </div>

                <hr />
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        @Html.ActionLink("Отменить", "List", null, new { @class = "btn btn-default" })
                        @Html.ActionLink("Удалить пост", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
                        <input type="submit" value="Сохранить изменения" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>


    </div>


}


<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Posts/Index.cshtml
@using Blog.Models
@using PagedList.Mvc;

@model PagedList.IPagedList<Post>

@{
    ViewBag.Title = "Posts";
}

<h2>Новости</h2>

<p>
    @Html.ActionLink("Создать новый пост", "Create") |
    @Html.ActionLink("Редактировать посты", "List") 
</p>

<div class="container">
    @foreach (Post post in Model)
    {

        <h5><small>@post.Date</small></h5>
        <h2>@post.Title</h2>
        <p>@post.Description</p>
        <p>
            @Html.ActionLink("Читать далее", "Show", new { id = post.Id })
            <span class="glyphicon glyphicon-menu-down"></span>
        </p>
        <hr/>
    }

    @if (Model.PageCount > 1)
    {
        @:Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    }


</div>

Blog/Views/Posts/List.cshtml
@using Blog.Models
@using PagedList.Mvc;

@model PagedList.IPagedList<Post>

@{
    ViewBag.Title = "Редактирование постов";
}

<h2>Редактирование постов</h2>

<p>Всего постов: @ViewBag.PostsCount</p>
<p>
    @Html.ActionLink("Показать посты", "Index", null, new { @class = "btn btn-default" })
    @Html.ActionLink("Создать новый пост", "Create",null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
    </tr>

    @foreach (var post in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => post.Date)
            </td>
            <td>
                @Html.ActionLink(post.Title, "Details", new {id = post.Id})
            </td>
        </tr>
    }





</table>

@if (Model.PageCount > 1)
{
    @:Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("List", new {page}))
}

Blog/Views/Posts/Show.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Post";
}

<br>

<div class="container">

    <h5><small>@Model.Date</small></h5>
    <h2>@Model.Title</h2>
    <p>@Model.Text</p>
    <hr/>
    <p>
        <span class="glyphicon glyphicon-menu-left"></span>
        @Html.ActionLink("Все новости", "Index", "Posts")
    </p>

</div>

<hr/>
@if (Model.AllowComments)
{
    @Html.Action("ListPartial", "Comments", new {id = Model.Id})
    @Html.Action("CreatePartial", "Comments", new {id = Model.Id})
}